Fix a click through bug for combobox lists in addon window
Return-To-The-Roots/s25client pull request #1318
Opened 2020-12-18 12:01 UTC by JonathanSteinbuch

As the title says, the addon options window has a bug where you can click through a combo box list item and also select the option below. This commit fixes this by not only locking the list region for the parent of the list, but recursively for all parents.

2020-12-18 13:04 UTC, Flamefire requested changes
Good catch! I'd just like the braces removed for the single line if as is done for all other places in the surrounding code.
Note: merging is going to take a bit as I'm currently replacing travis CI

2020-12-19 17:45 UTC, Flamefire commented
Can you rebase please so the new CI runs?

2020-12-19 19:52 UTC, Flamefire commented
Something is odd, close and reopen to retrigger CI

2020-12-19 19:54 UTC, Flamefire commented
@Flow86 Can you check where the `Linux_And_OSX ` CI stuff comes from?  That looks like some stuff I had in my branch but removed. To me the 3 PRs look good

2020-12-19 19:55 UTC, Flamefire approved these changes

2020-12-20 08:51 UTC, Flow86 commented
> 
> 
> @Flow86 Can you check where the `Linux_And_OSX ` CI stuff comes from? That looks like some stuff I had in my branch but removed. To me the 2 PRs look good

which ones should be active?

2020-12-20 08:55 UTC, merged