fix AI interaction with granite mines with enabled Inexhaustible gran…
Return-To-The-Roots/s25client pull request #1651
Opened 2024-03-09 02:48 UTC by desofity

Hello!

Currently if addon "Inexhaustible granite mines" is enabled, AI place granite mine on any available mine place. (Because method "SimpleFindPosition" is used instead of "FindBestPosition") Then after building of mine is complete, AI reailizes that there is no resource available and demolishes granite mine.

The code comment says that "inexhaustible granite mines do not require granite" but i can't find any code line that proves that.
If that was originally intended to allow building granite mine on any mine place if addon is enabled, we need to add some code in resource map generator, probably. But I decided that this was not intended and just removed condition.

2024-03-09 08:45 UTC, Flow86 submitted a review, later dismissed
you're totally right, inexhaustible granite mines only says that a valid granite mine never runs out of stone, not that you can place it everywhere.

2024-03-09 09:19 UTC, Spikeone commented
well @Flow86 and @desofity - the AI currently correclty implements the addon - since thats how I implemented the addon once (just place graninte mines anywhere). At some point @Flamefire 'fixed' it since the description wasn't clear and it sounded like it is a minimal version of the inexhaustible mines addon. But yeah, the fix is probably fine for now, I need to add my settlers IV mining addons which also solves that addon issue :D

2024-03-09 10:13 UTC, Flamefire requested changes

2024-03-09 10:13 UTC, Flamefire commented on libs/s25main/ai/aijh/AIPlayerJH.cpp
> +			foundPos = FindBestPosition(around, AIResource::Granite, BuildingQuality::Mine, searchRadius);
Only the indentation is off:
```suggestion
          foundPos = FindBestPosition(around, AIResource::Granite, BuildingQuality::Mine, searchRadius);
```

2024-03-09 15:54 UTC, Flamefire approved these changes
Thanks!

2024-03-11 06:14 UTC, Flow86 approved these changes

2024-03-11 06:45 UTC, merged